[book]
authors = ["Nick Rossik"]
title = "Современное тестирование Swift Testing"
language = "ru"
multilingual = false
src = "src"

[build]
build-dir = "docs"
create-missing = false

[preprocessor.alerts]

# [output.epub]
# cover-image = "assets/Cover.png"
